// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: V2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0D0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 1 );
lv_obj_set_y( ui_Label1, -144 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"HerbieTest");

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -40 );
lv_obj_set_y( ui_Label2, -108 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Temp");

ui_tempN = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_tempN, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tempN, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tempN, -41 );
lv_obj_set_y( ui_tempN, -71 );
lv_obj_set_align( ui_tempN, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_tempN, lv_color_hex(0xFF9B00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tempN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 35 );
lv_obj_set_y( ui_Label3, -107 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Hum");

ui_humN = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_humN, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humN, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_humN, 34 );
lv_obj_set_y( ui_humN, -71 );
lv_obj_set_align( ui_humN, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_humN, lv_color_hex(0x00AFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_humN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_moistG = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_moistG, 137);
lv_obj_set_height( ui_moistG, 150);
lv_obj_set_x( ui_moistG, 0 );
lv_obj_set_y( ui_moistG, 39 );
lv_obj_set_align( ui_moistG, LV_ALIGN_CENTER );
lv_arc_set_range(ui_moistG, 0,255);
lv_arc_set_value(ui_moistG, 50);


ui_moistN = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_moistN, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moistN, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moistN, -1 );
lv_obj_set_y( ui_moistN, 28 );
lv_obj_set_align( ui_moistN, LV_ALIGN_CENTER );
lv_label_set_text(ui_moistN,"Moist");

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 0 );
lv_obj_set_y( ui_Label4, 103 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Gas Amount");

ui_gasN = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_gasN, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gasN, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gasN, -2 );
lv_obj_set_y( ui_gasN, 130 );
lv_obj_set_align( ui_gasN, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_gasN, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gasN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


}
