// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 1 );
lv_obj_set_y( ui_Label1, -144 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"HerbieTest");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -1 );
lv_obj_set_y( ui_Label3, 28 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Moist");

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 137);
lv_obj_set_height( ui_Arc1, 150);
lv_obj_set_x( ui_Arc1, 0 );
lv_obj_set_y( ui_Arc1, 39 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc1, 0,255);
lv_arc_set_value(ui_Arc1, 50);


ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 121);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, -1 );
lv_obj_set_y( ui_Button1, 116 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xED0808), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 1 );
lv_obj_set_y( ui_Label2, 118 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Who's there?");

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -40 );
lv_obj_set_y( ui_Label4, -108 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Temp");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 35 );
lv_obj_set_y( ui_Label5, -107 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Hum");

ui_temp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temp, -41 );
lv_obj_set_y( ui_temp, -71 );
lv_obj_set_align( ui_temp, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFF9B00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_hum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hum, 34 );
lv_obj_set_y( ui_hum, -71 );
lv_obj_set_align( ui_hum, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_hum, lv_color_hex(0x00AFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_hum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


}
